language: python
python:
  - "3.5"

install:
# Get newest node
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - make

# command to run tests
script:
  # Start fake x for integration tests
  - "sh -e /etc/init.d/xvfb start"
  - "export DISPLAY=:99.0"
  - make test
